basePath: /v1
consumes:
- application/json
definitions:
  http.InternalServerErrorResponse:
    properties:
      error:
        example: the server encountered a problem and could not process your request
        type: string
    type: object
  http.Response:
    properties:
      error:
        example: message
        type: string
    type: object
  model.CreateUser:
    properties:
      passportNumber:
        example: 1234 567890
        maxLength: 11
        minLength: 11
        type: string
    required:
    - passportNumber
    type: object
  model.User:
    properties:
      address:
        example: г. Москва, ул. Ленина, д. 5, кв. 1
        type: string
      id:
        example: 1
        minimum: 1
        type: integer
      name:
        example: Иван
        maxLength: 255
        type: string
      passport_number:
        example: "567890"
        maxLength: 6
        minLength: 6
        type: string
      passport_series:
        example: "1234"
        maxLength: 4
        minLength: 4
        type: string
      patronymic:
        example: Иванович
        maxLength: 255
        type: string
      surname:
        example: Иванов
        maxLength: 255
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  title: Time Tracker API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Retrieve users info with filtering and pagination support
      parameters:
      - example: 1
        in: query
        minimum: 1
        name: page
        type: integer
      - example: 10
        in: query
        minimum: 1
        name: page_size
        type: integer
      - example: г. Москва, ул. Ленина, д. 5, кв. 1
        in: query
        name: address
        type: string
      - example: 1
        in: query
        minimum: 1
        name: id
        type: integer
      - example: Иван
        in: query
        maxLength: 255
        name: name
        type: string
      - example: "567890"
        in: query
        maxLength: 6
        minLength: 6
        name: passport_number
        type: string
      - example: "1234"
        in: query
        maxLength: 4
        minLength: 4
        name: passport_series
        type: string
      - example: Иванович
        in: query
        maxLength: 255
        name: patronymic
        type: string
      - example: Иванов
        in: query
        maxLength: 255
        name: surname
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.InternalServerErrorResponse'
      summary: Get users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create user by passport number
      parameters:
      - description: Full Passport Number
        in: body
        name: passportNumber
        required: true
        schema:
          $ref: '#/definitions/model.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.InternalServerErrorResponse'
      summary: Create a user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.InternalServerErrorResponse'
      summary: Delete a user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get user by id
      parameters:
      - description: User ID
        example: 1
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.InternalServerErrorResponse'
      summary: Get user
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Update all or several user fields
      parameters:
      - description: User ID
        example: 1
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.InternalServerErrorResponse'
      summary: Update a user
      tags:
      - users
produces:
- application/json
swagger: "2.0"
